defaults:
  - process: process1
  - model: model1
  - _self_

raw:
  path: data/raw/raw_data.csv

processed:
  dir: data/processed
  name: processed.parquet
  path: ${processed.dir}/${processed.name}

final:
  dir: data/final
  name: final.parquet
  path: ${final.dir}/${final.name}
